[package]
name = "music-lib-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.9"
id3 = "1.14.0"
rodio = "0.19.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
structopt = "0.3.26"
walkdir = "2.5.0"
